const VOCAB_DATA = {
  cambridge: {
    13: {
      1: {},
      2: {},
      3: {},
      4: {},
    },
    14: { 1:{}, 2:{}, 3:{}, 4:{} },
    15: { 1:{}, 2:{}, 3:{}, 4:{} },
    16: { 1:{}, 2:{}, 3:{}, 4:{} },
    17: { 1:{}, 2:{}, 3:{}, 4:{} },
    18: { 1:{}, 2:{}, 3:{}, 4:{} },
    19: { 1:{}, 2:{}, 3:{}, 4:{} },
    20: { 1:{}, 2:{}, 3:{}, 4:{} },
  },
  road: {
    1:{
      "chrono-rhythms":         { meaning: "nhịp sinh học theo thời gian", type: "phrase", collocation: "chrono-rhythms of the body", example: "Scientists study chrono-rhythms to understand how time affects living things." , connotation: "neutral"},
      "flora and fauna":        { meaning: "thực vật và động vật", type: "phrase", collocation: "local flora and fauna", example: "The rainforest is home to extraordinary flora and fauna." , connotation: "neutral"},
      "tidal":                  { meaning: "thuộc về thủy triều", type: "adjective", collocation: "tidal patterns", example: "Tidal forces influence the behaviour of many coastal animals." , connotation: "neutral"},
      "dawn and dusk":          { meaning: "bình minh và hoàng hôn", type: "phrase", collocation: "active at dawn and dusk", example: "Many birds are most active at dawn and dusk." , connotation: "neutral"},
      "circadian rhythm":       { meaning: "nhịp sinh học ngày đêm", type: "phrase", collocation: "disrupt the circadian rhythm", example: "Shift workers often struggle because their circadian rhythm is disrupted." , connotation: "neutral"},
      "become alert":           { meaning: "trở nên tỉnh táo/cảnh giác", type: "phrase", collocation: "become alert to danger", example: "Animals become alert when they sense a predator nearby." , connotation: "positive"},
      "benign":                 { meaning: "lành tính, vô hại", type: "adjective", antonym: "malignant", collocation: "benign tumour", example: "The doctor confirmed the growth was benign and required no treatment." , connotation: "positive"},
      "malleable":              { meaning: "dễ uốn nắn, linh hoạt", type: "adjective", antonym: "rigid", collocation: "malleable behaviour", example: "Young children are highly malleable and absorb new information quickly." , connotation: "positive"},
      "ripen":                  { meaning: "chín (quả/hoa màu)", type: "verb", collocation: "ripen naturally", example: "Fruit allowed to ripen naturally has a much better flavour." , connotation: "positive"},
      "subjugate":              { meaning: "khuất phục, chinh phục", type: "verb", antonym: "liberate", collocation: "subjugate a population", example: "Colonial powers sought to subjugate indigenous peoples." , connotation: "negative"},
      "deleterious effects":    { meaning: "tác hại có hại, tác động tiêu cực", type: "phrase", collocation: "deleterious effects on health", example: "Sleep deprivation has deleterious effects on cognitive performance." , connotation: "negative"},
      "shed some extra pounds": { meaning: "giảm cân", type: "phrase", collocation: "shed some extra pounds before summer", example: "She followed a strict diet to shed some extra pounds before the marathon." , connotation: "positive"},
      "soluble":                { meaning: "tan được, hòa tan được", type: "adjective", antonym: "insoluble", collocation: "water-soluble vitamins", example: "Vitamin C is water-soluble and must be replenished daily." , connotation: "neutral"},
      "steer clear of":         { meaning: "tránh xa, né tránh", type: "phrase", collocation: "steer clear of trouble", example: "The doctor advised him to steer clear of processed foods." , connotation: "neutral"},
      "digestive tract":        { meaning: "đường tiêu hóa", type: "phrase", collocation: "healthy digestive tract", example: "A high-fibre diet supports a healthy digestive tract." , connotation: "neutral"},
      "startle":                { meaning: "làm giật mình, giật nẩy", type: "verb", antonym: "soothe", collocation: "startle a sleeping animal", example: "A loud noise can startle even the calmest of animals." , connotation: "negative"},
      "lurch":                  { meaning: "lảo đảo, nghiêng ngả đột ngột", type: "verb", collocation: "lurch forward", example: "The bus lurched forward as the driver braked suddenly." , connotation: "negative"},
      "indifference":           { meaning: "sự thờ ơ, vô cảm", type: "noun", antonym: "concern", collocation: "public indifference", example: "The politician's indifference to poverty shocked many voters." , connotation: "negative"},
      "feats of":               { meaning: "thành tích về, kỳ tích về", type: "phrase", collocation: "feats of engineering", example: "The ancient pyramids represent remarkable feats of engineering." , connotation: "positive"},
      "lobotomy":               { meaning: "phẫu thuật não tiền trán", type: "noun", collocation: "perform a lobotomy", example: "The lobotomy was once used as a controversial treatment for mental illness." , connotation: "negative"},
      "rod":                    { meaning: "tế bào que (trong mắt)/gậy", type: "noun", collocation: "rod cells in the eye", example: "Rod cells in the retina allow us to see in low light conditions." , connotation: "neutral"},
      "demise":                 { meaning: "sự sụp đổ, cái chết/kết thúc", type: "noun", antonym: "rise", collocation: "the demise of an industry", example: "The demise of traditional manufacturing led to widespread unemployment." , connotation: "negative"},
      "odour":                  { meaning: "mùi (thường khó chịu)", type: "noun", antonym: "fragrance", collocation: "unpleasant odour", example: "An unpleasant odour indicated that the food had spoiled." , connotation: "negative"},
      "radioactive decay":      { meaning: "phân rã phóng xạ", type: "phrase", collocation: "rate of radioactive decay", example: "Scientists use radioactive decay to estimate the age of fossils." , connotation: "neutral"},
      "adhere to":              { meaning: "tuân thủ, bám vào", type: "phrase", collocation: "adhere to guidelines", example: "All staff must adhere to the company's safety regulations." , connotation: "positive"},
      "coveting":               { meaning: "thèm muốn, thèm khát", type: "verb", collocation: "coveting material wealth", example: "He spent his life coveting the success of others rather than building his own." , connotation: "negative"},
      "dwindling":              { meaning: "ngày càng cạn kiệt, suy giảm dần", type: "adjective", antonym: "growing", collocation: "dwindling resources", example: "The team struggled on with dwindling supplies and no rescue in sight." , connotation: "negative"},
      "postponement":           { meaning: "sự trì hoãn, hoãn lại", type: "noun", antonym: "advancement", collocation: "postponement of a deadline", example: "The postponement of the exam gave students an extra week to prepare." , connotation: "negative"},
      "deflated":               { meaning: "xẹp xuống, mất nhuệ khí", type: "adjective", antonym: "elated", collocation: "feel deflated", example: "She felt deflated after receiving negative feedback on her project." , connotation: "negative"},
      "judiciously":            { meaning: "một cách sáng suốt, thận trọng", type: "adverb", antonym: "rashly", collocation: "use judiciously", example: "Resources must be used judiciously to ensure they last the whole year." , connotation: "positive"},
      "be prevailed upon":      { meaning: "bị thuyết phục, bị vận động", type: "phrase", collocation: "be prevailed upon to agree", example: "He was prevailed upon to donate his collection to the museum." , connotation: "neutral"},
      "incentives":             { meaning: "khuyến khích, động lực", type: "noun", antonym: "deterrents", collocation: "financial incentives", example: "The government offered financial incentives to encourage green energy adoption." , connotation: "positive"},
      "off-peak":               { meaning: "giờ thấp điểm", type: "adjective", collocation: "off-peak travel", example: "Tickets are cheaper if you travel off-peak." , connotation: "neutral"},
      "preliminary session":    { meaning: "buổi học sơ bộ/giới thiệu", type: "phrase", collocation: "attend a preliminary session", example: "All new students must attend a preliminary session before the course begins." , connotation: "neutral"},
      "positive reinforcement": { meaning: "củng cố tích cực", type: "phrase", collocation: "use positive reinforcement", example: "Teachers use positive reinforcement to encourage good behaviour in class." , connotation: "positive"},
      "tertiary education":     { meaning: "giáo dục bậc cao (đại học)", type: "phrase", collocation: "access to tertiary education", example: "Access to tertiary education remains unequal across different regions." , connotation: "positive"},
      "tailored to":            { meaning: "được thiết kế phù hợp với", type: "phrase", collocation: "tailored to individual needs", example: "The programme is tailored to the specific needs of adult learners." , connotation: "positive"},
      "protagonists":           { meaning: "nhân vật chính", type: "noun", collocation: "the story's protagonists", example: "The novel's protagonists struggle with identity and belonging." , connotation: "neutral"},
      "orphaned":               { meaning: "mồ côi", type: "adjective", collocation: "orphaned children", example: "The charity supports orphaned children in conflict zones." , connotation: "negative"},
      "cholera outbreak":       { meaning: "dịch tả bùng phát", type: "phrase", collocation: "contain a cholera outbreak", example: "Aid workers rushed to contain a cholera outbreak following the flood." , connotation: "negative"},
      "permanently crippled":   { meaning: "tàn tật vĩnh viễn", type: "phrase", collocation: "left permanently crippled", example: "The accident left him permanently crippled and unable to work." , connotation: "negative"},
      "fulfilled":              { meaning: "viên mãn, được thỏa mãn", type: "adjective", antonym: "unfulfilled", collocation: "feel fulfilled", example: "She finally felt fulfilled after dedicating her life to teaching." , connotation: "positive"},
      "narrative techniques":   { meaning: "kỹ thuật kể chuyện", type: "phrase", collocation: "employ narrative techniques", example: "The author employs various narrative techniques to build suspense." , connotation: "neutral"},
      "motif":                  { meaning: "mô-típ, chủ đề lặp lại", type: "noun", collocation: "recurring motif", example: "Water is a recurring motif throughout the novel, symbolising change." , connotation: "neutral"},
      "steeped in secrecy":     { meaning: "đắm chìm trong bí mật", type: "phrase", collocation: "steeped in secrecy", example: "The organisation's origins are steeped in secrecy and speculation." , connotation: "neutral"},
      "stifle the development": { meaning: "kìm hãm sự phát triển", type: "phrase", collocation: "stifle the development of talent", example: "Overly strict rules can stifle the development of creativity in students." , connotation: "negative"},
      "human companionship":    { meaning: "sự đồng hành của con người", type: "phrase", collocation: "crave human companionship", example: "Isolated for months, he deeply craved human companionship." , connotation: "positive"},
      "present hedonists":      { meaning: "người theo chủ nghĩa hưởng thụ hiện tại", type: "phrase", collocation: "present hedonists seek pleasure", example: "Present hedonists prioritise immediate pleasure over long-term consequences." , connotation: "neutral"},
      "planners and go-getters":{ meaning: "người lập kế hoạch và cầu tiến", type: "phrase", collocation: "society needs planners and go-getters", example: "Society benefits from both planners and go-getters working together." , connotation: "positive"},
      "resist temptation":      { meaning: "chống lại cám dỗ", type: "phrase", collocation: "resist temptation effectively", example: "Children who can resist temptation tend to achieve better long-term outcomes." , connotation: "positive"},
      "live virtuously":        { meaning: "sống đức hạnh, đạo đức", type: "phrase", collocation: "live virtuously", example: "Many religions teach followers to live virtuously and serve others." , connotation: "positive"},
      "stem from":              { meaning: "bắt nguồn từ", type: "phrase", collocation: "stem from childhood", example: "Many adult anxieties stem from unresolved childhood experiences." , connotation: "neutral"},
      "prevention education":   { meaning: "giáo dục phòng ngừa", type: "phrase", collocation: "invest in prevention education", example: "Prevention education reduces long-term healthcare costs significantly." , connotation: "positive"},
      "present-orientated":     { meaning: "định hướng hiện tại", type: "phrase", collocation: "present-orientated thinking", example: "Present-orientated people focus on today rather than planning for the future." , connotation: "neutral"},
      "persist with the behaviour": { meaning: "tiếp tục duy trì hành vi", type: "phrase", collocation: "persist with the behaviour despite setbacks", example: "Addicts often persist with the behaviour even when it causes clear harm." , connotation: "neutral"},
      "potential fall-out":     { meaning: "hậu quả tiềm ẩn", type: "phrase", collocation: "potential fall-out from a decision", example: "Leaders must consider the potential fall-out from controversial policies." , connotation: "negative"},
      "labouring away":         { meaning: "lao động miệt mài", type: "phrase", collocation: "labouring away at a task", example: "She spent years labouring away at her research with little recognition." }
    , connotation: "neutral"},
    2:{}, 3:{}, 4:{}, 5:{}, 6:{}
  }
};
