const VOCAB_DATA = {
  cambridge: {
    13: {
      1: {
        "authorise":     { meaning: "cho phép, cấp quyền",    type: "verb",      antonym: "forbid",      collocation: "authorise a payment",       example: "She was not authorised to enter the building." },
        "stimulus":      { meaning: "kích thích, tác nhân",   type: "noun",      antonym: "deterrent",   collocation: "provide a stimulus for",    example: "Boredom can act as a stimulus for creativity." },
        "innate":        { meaning: "bẩm sinh, vốn có",       type: "adjective", antonym: "acquired",    collocation: "innate ability",            example: "Children have an innate curiosity about the world." },
        "deliberate":    { meaning: "có chủ ý, cố tình",      type: "adjective", antonym: "accidental",  collocation: "a deliberate attempt",      example: "It was a deliberate effort to mislead the public." },
        "incorporate":   { meaning: "tích hợp, đưa vào",      type: "verb",      antonym: "exclude",     collocation: "incorporate into a design", example: "The new model incorporates several safety features." },
        "perception":    { meaning: "nhận thức, cảm nhận",    type: "noun",      antonym: "ignorance",   collocation: "public perception",         example: "Public perception of the issue has shifted dramatically." },
        "substantial":   { meaning: "đáng kể, lớn",           type: "adjective", antonym: "negligible",  collocation: "substantial evidence",      example: "There was a substantial increase in sales last quarter." },
        "replicate":     { meaning: "sao chép, lặp lại",      type: "verb",      antonym: "originate",   collocation: "replicate an experiment",   example: "Other scientists failed to replicate the findings." },
        "phenomenon":    { meaning: "hiện tượng",              type: "noun",                              collocation: "a rare phenomenon",         example: "Climate change is a truly global phenomenon." },
        "contemporary":  { meaning: "đương đại, hiện đại",    type: "adjective", antonym: "ancient",     collocation: "contemporary art",          example: "Contemporary art often challenges traditional values." },
        "controversial": { meaning: "gây tranh cãi",           type: "adjective", antonym: "agreed",      collocation: "a controversial decision",  example: "The policy proved deeply controversial." },
        "mechanism":     { meaning: "cơ chế, cách thức",      type: "noun",                              collocation: "a mechanism for change",    example: "We need a better mechanism for handling complaints." },
        "cognitive":     { meaning: "thuộc về nhận thức",     type: "adjective",                         collocation: "cognitive skills",          example: "Cognitive development is crucial in early childhood." },
        "abundance":     { meaning: "sự dồi dào, phong phú",  type: "noun",      antonym: "scarcity",    collocation: "in abundance",              example: "Wildlife exists here in abundance." },
        "attribute":     { meaning: "quy cho, gắn cho",       type: "verb",                              collocation: "attribute success to",      example: "She attributed her success to hard work." },
      },
      2: {},
      3: {},
      4: {},
    },
    14: { 1:{}, 2:{}, 3:{}, 4:{} },
    15: { 1:{}, 2:{}, 3:{}, 4:{} },
    16: { 1:{}, 2:{}, 3:{}, 4:{} },
    17: { 1:{}, 2:{}, 3:{}, 4:{} },
    18: { 1:{}, 2:{}, 3:{}, 4:{} },
    19: { 1:{}, 2:{}, 3:{}, 4:{} },
    20: { 1:{}, 2:{}, 3:{}, 4:{} },
  },
  road: {
    1:{
      "chrono-rhythms":         { meaning: "nhịp sinh học theo thời gian", type: "phrase", collocation: "chrono-rhythms of the body", example: "Scientists study chrono-rhythms to understand how time affects living things." },
      "flora and fauna":        { meaning: "thực vật và động vật", type: "phrase", collocation: "local flora and fauna", example: "The rainforest is home to extraordinary flora and fauna." },
      "tidal":                  { meaning: "thuộc về thủy triều", type: "adjective", collocation: "tidal patterns", example: "Tidal forces influence the behaviour of many coastal animals." },
      "dawn and dusk":          { meaning: "bình minh và hoàng hôn", type: "phrase", collocation: "active at dawn and dusk", example: "Many birds are most active at dawn and dusk." },
      "circadian rhythm":       { meaning: "nhịp sinh học ngày đêm", type: "phrase", collocation: "disrupt the circadian rhythm", example: "Shift workers often struggle because their circadian rhythm is disrupted." },
      "become alert":           { meaning: "trở nên tỉnh táo/cảnh giác", type: "phrase", collocation: "become alert to danger", example: "Animals become alert when they sense a predator nearby." },
      "benign":                 { meaning: "lành tính, vô hại", type: "adjective", antonym: "malignant", collocation: "benign tumour", example: "The doctor confirmed the growth was benign and required no treatment." },
      "malleable":              { meaning: "dễ uốn nắn, linh hoạt", type: "adjective", antonym: "rigid", collocation: "malleable behaviour", example: "Young children are highly malleable and absorb new information quickly." },
      "ripen":                  { meaning: "chín (quả/hoa màu)", type: "verb", collocation: "ripen naturally", example: "Fruit allowed to ripen naturally has a much better flavour." },
      "subjugate":              { meaning: "khuất phục, chinh phục", type: "verb", antonym: "liberate", collocation: "subjugate a population", example: "Colonial powers sought to subjugate indigenous peoples." },
      "deleterious effects":    { meaning: "tác hại có hại, tác động tiêu cực", type: "phrase", collocation: "deleterious effects on health", example: "Sleep deprivation has deleterious effects on cognitive performance." },
      "shed some extra pounds": { meaning: "giảm cân", type: "phrase", collocation: "shed some extra pounds before summer", example: "She followed a strict diet to shed some extra pounds before the marathon." },
      "soluble":                { meaning: "tan được, hòa tan được", type: "adjective", antonym: "insoluble", collocation: "water-soluble vitamins", example: "Vitamin C is water-soluble and must be replenished daily." },
      "steer clear of":         { meaning: "tránh xa, né tránh", type: "phrase", collocation: "steer clear of trouble", example: "The doctor advised him to steer clear of processed foods." },
      "digestive tract":        { meaning: "đường tiêu hóa", type: "phrase", collocation: "healthy digestive tract", example: "A high-fibre diet supports a healthy digestive tract." },
      "startle":                { meaning: "làm giật mình, giật nẩy", type: "verb", antonym: "soothe", collocation: "startle a sleeping animal", example: "A loud noise can startle even the calmest of animals." },
      "lurch":                  { meaning: "lảo đảo, nghiêng ngả đột ngột", type: "verb", collocation: "lurch forward", example: "The bus lurched forward as the driver braked suddenly." },
      "indifference":           { meaning: "sự thờ ơ, vô cảm", type: "noun", antonym: "concern", collocation: "public indifference", example: "The politician's indifference to poverty shocked many voters." },
      "feats of":               { meaning: "thành tích về, kỳ tích về", type: "phrase", collocation: "feats of engineering", example: "The ancient pyramids represent remarkable feats of engineering." },
      "lobotomy":               { meaning: "phẫu thuật não tiền trán", type: "noun", collocation: "perform a lobotomy", example: "The lobotomy was once used as a controversial treatment for mental illness." },
      "rod":                    { meaning: "tế bào que (trong mắt)/gậy", type: "noun", collocation: "rod cells in the eye", example: "Rod cells in the retina allow us to see in low light conditions." },
      "demise":                 { meaning: "sự sụp đổ, cái chết/kết thúc", type: "noun", antonym: "rise", collocation: "the demise of an industry", example: "The demise of traditional manufacturing led to widespread unemployment." },
      "odour":                  { meaning: "mùi (thường khó chịu)", type: "noun", antonym: "fragrance", collocation: "unpleasant odour", example: "An unpleasant odour indicated that the food had spoiled." },
      "radioactive decay":      { meaning: "phân rã phóng xạ", type: "phrase", collocation: "rate of radioactive decay", example: "Scientists use radioactive decay to estimate the age of fossils." },
      "adhere to":              { meaning: "tuân thủ, bám vào", type: "phrase", collocation: "adhere to guidelines", example: "All staff must adhere to the company's safety regulations." },
      "coveting":               { meaning: "thèm muốn, thèm khát", type: "verb", collocation: "coveting material wealth", example: "He spent his life coveting the success of others rather than building his own." },
      "dwindling":              { meaning: "ngày càng cạn kiệt, suy giảm dần", type: "adjective", antonym: "growing", collocation: "dwindling resources", example: "The team struggled on with dwindling supplies and no rescue in sight." },
      "postponement":           { meaning: "sự trì hoãn, hoãn lại", type: "noun", antonym: "advancement", collocation: "postponement of a deadline", example: "The postponement of the exam gave students an extra week to prepare." },
      "deflated":               { meaning: "xẹp xuống, mất nhuệ khí", type: "adjective", antonym: "elated", collocation: "feel deflated", example: "She felt deflated after receiving negative feedback on her project." },
      "judiciously":            { meaning: "một cách sáng suốt, thận trọng", type: "adverb", antonym: "rashly", collocation: "use judiciously", example: "Resources must be used judiciously to ensure they last the whole year." },
      "be prevailed upon":      { meaning: "bị thuyết phục, bị vận động", type: "phrase", collocation: "be prevailed upon to agree", example: "He was prevailed upon to donate his collection to the museum." },
      "incentives":             { meaning: "khuyến khích, động lực", type: "noun", antonym: "deterrents", collocation: "financial incentives", example: "The government offered financial incentives to encourage green energy adoption." },
      "off-peak":               { meaning: "giờ thấp điểm", type: "adjective", collocation: "off-peak travel", example: "Tickets are cheaper if you travel off-peak." },
      "preliminary session":    { meaning: "buổi học sơ bộ/giới thiệu", type: "phrase", collocation: "attend a preliminary session", example: "All new students must attend a preliminary session before the course begins." },
      "positive reinforcement": { meaning: "củng cố tích cực", type: "phrase", collocation: "use positive reinforcement", example: "Teachers use positive reinforcement to encourage good behaviour in class." },
      "tertiary education":     { meaning: "giáo dục bậc cao (đại học)", type: "phrase", collocation: "access to tertiary education", example: "Access to tertiary education remains unequal across different regions." },
      "tailored to":            { meaning: "được thiết kế phù hợp với", type: "phrase", collocation: "tailored to individual needs", example: "The programme is tailored to the specific needs of adult learners." },
      "protagonists":           { meaning: "nhân vật chính", type: "noun", collocation: "the story's protagonists", example: "The novel's protagonists struggle with identity and belonging." },
      "orphaned":               { meaning: "mồ côi", type: "adjective", collocation: "orphaned children", example: "The charity supports orphaned children in conflict zones." },
      "cholera outbreak":       { meaning: "dịch tả bùng phát", type: "phrase", collocation: "contain a cholera outbreak", example: "Aid workers rushed to contain a cholera outbreak following the flood." },
      "permanently crippled":   { meaning: "tàn tật vĩnh viễn", type: "phrase", collocation: "left permanently crippled", example: "The accident left him permanently crippled and unable to work." },
      "fulfilled":              { meaning: "viên mãn, được thỏa mãn", type: "adjective", antonym: "unfulfilled", collocation: "feel fulfilled", example: "She finally felt fulfilled after dedicating her life to teaching." },
      "narrative techniques":   { meaning: "kỹ thuật kể chuyện", type: "phrase", collocation: "employ narrative techniques", example: "The author employs various narrative techniques to build suspense." },
      "motif":                  { meaning: "mô-típ, chủ đề lặp lại", type: "noun", collocation: "recurring motif", example: "Water is a recurring motif throughout the novel, symbolising change." },
      "steeped in secrecy":     { meaning: "đắm chìm trong bí mật", type: "phrase", collocation: "steeped in secrecy", example: "The organisation's origins are steeped in secrecy and speculation." },
      "stifle the development": { meaning: "kìm hãm sự phát triển", type: "phrase", collocation: "stifle the development of talent", example: "Overly strict rules can stifle the development of creativity in students." },
      "human companionship":    { meaning: "sự đồng hành của con người", type: "phrase", collocation: "crave human companionship", example: "Isolated for months, he deeply craved human companionship." },
      "present hedonists":      { meaning: "người theo chủ nghĩa hưởng thụ hiện tại", type: "phrase", collocation: "present hedonists seek pleasure", example: "Present hedonists prioritise immediate pleasure over long-term consequences." },
      "planners and go-getters":{ meaning: "người lập kế hoạch và cầu tiến", type: "phrase", collocation: "society needs planners and go-getters", example: "Society benefits from both planners and go-getters working together." },
      "resist temptation":      { meaning: "chống lại cám dỗ", type: "phrase", collocation: "resist temptation effectively", example: "Children who can resist temptation tend to achieve better long-term outcomes." },
      "live virtuously":        { meaning: "sống đức hạnh, đạo đức", type: "phrase", collocation: "live virtuously", example: "Many religions teach followers to live virtuously and serve others." },
      "stem from":              { meaning: "bắt nguồn từ", type: "phrase", collocation: "stem from childhood", example: "Many adult anxieties stem from unresolved childhood experiences." },
      "prevention education":   { meaning: "giáo dục phòng ngừa", type: "phrase", collocation: "invest in prevention education", example: "Prevention education reduces long-term healthcare costs significantly." },
      "present-orientated":     { meaning: "định hướng hiện tại", type: "phrase", collocation: "present-orientated thinking", example: "Present-orientated people focus on today rather than planning for the future." },
      "persist with the behaviour": { meaning: "tiếp tục duy trì hành vi", type: "phrase", collocation: "persist with the behaviour despite setbacks", example: "Addicts often persist with the behaviour even when it causes clear harm." },
      "potential fall-out":     { meaning: "hậu quả tiềm ẩn", type: "phrase", collocation: "potential fall-out from a decision", example: "Leaders must consider the potential fall-out from controversial policies." },
      "labouring away":         { meaning: "lao động miệt mài", type: "phrase", collocation: "labouring away at a task", example: "She spent years labouring away at her research with little recognition." }
    },
    2:{}, 3:{}, 4:{}, 5:{}, 6:{}
  }
};

